name: xmem_
channels:
  - nvidia/label/cuda-12.4.0
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - binutils=2.44=h4852527_5
  - binutils_impl_linux-64=2.44=h4b9a079_2
  - binutils_linux-64=2.44=hc03a8fd_2
  - bzip2=1.0.8=h5eee18b_6
  - c-compiler=1.11.0=h4d9bdce_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - conda-gcc-specs=14.3.0=hb991d5c_7
  - cuda-cccl=12.4.99=0
  - cuda-command-line-tools=12.4.0=0
  - cuda-compiler=12.4.0=0
  - cuda-cudart=12.4.99=0
  - cuda-cudart-dev=12.4.99=0
  - cuda-cudart-static=12.4.99=0
  - cuda-cuobjdump=12.4.99=0
  - cuda-cupti=12.4.99=0
  - cuda-cupti-static=12.4.99=0
  - cuda-cuxxfilt=12.4.99=0
  - cuda-documentation=12.4.99=0
  - cuda-driver-dev=12.4.99=0
  - cuda-gdb=12.4.99=0
  - cuda-libraries=12.4.0=0
  - cuda-libraries-dev=12.4.0=0
  - cuda-libraries-static=12.4.0=0
  - cuda-nsight=12.4.99=0
  - cuda-nsight-compute=12.4.0=0
  - cuda-nvcc=12.4.99=0
  - cuda-nvdisasm=12.4.99=0
  - cuda-nvml-dev=12.4.99=0
  - cuda-nvprof=12.4.99=0
  - cuda-nvprune=12.4.99=0
  - cuda-nvrtc=12.4.99=0
  - cuda-nvrtc-dev=12.4.99=0
  - cuda-nvrtc-static=12.4.99=0
  - cuda-nvtx=12.4.99=0
  - cuda-nvvp=12.4.99=0
  - cuda-opencl=12.4.99=0
  - cuda-opencl-dev=12.4.99=0
  - cuda-profiler-api=12.4.99=0
  - cuda-sanitizer-api=12.4.99=0
  - cuda-toolkit=12.4.0=0
  - cuda-tools=12.4.0=0
  - cuda-visual-tools=12.4.0=0
  - cxx-compiler=1.11.0=hfcd1e18_0
  - expat=2.7.3=h3385a95_0
  - gcc=14.3.0=h76bdaa0_7
  - gcc_impl_linux-64=14.3.0=hd9e9e21_7
  - gcc_linux-64=14.3.0=h298d278_13
  - gds-tools=1.9.0.20=0
  - gxx=14.3.0=he448592_7
  - gxx_impl_linux-64=14.3.0=he663afc_7
  - gxx_linux-64=14.3.0=hed40740_13
  - kernel-headers_linux-64=5.14.0=he073ed8_2
  - ld_impl_linux-64=2.44=h153f514_2
  - libcublas=12.4.2.65=0
  - libcublas-dev=12.4.2.65=0
  - libcublas-static=12.4.2.65=0
  - libcufft=11.2.0.44=0
  - libcufft-dev=11.2.0.44=0
  - libcufft-static=11.2.0.44=0
  - libcufile=1.9.0.20=0
  - libcufile-dev=1.9.0.20=0
  - libcufile-static=1.9.0.20=0
  - libcurand=10.3.5.119=0
  - libcurand-dev=10.3.5.119=0
  - libcurand-static=10.3.5.119=0
  - libcusolver=11.6.0.99=0
  - libcusolver-dev=11.6.0.99=0
  - libcusolver-static=11.6.0.99=0
  - libcusparse=12.3.0.142=0
  - libcusparse-dev=12.3.0.142=0
  - libcusparse-static=12.3.0.142=0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-devel_linux-64=14.3.0=h85bb3a7_107
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libnpp=12.2.5.2=0
  - libnpp-dev=12.2.5.2=0
  - libnpp-static=12.2.5.2=0
  - libnsl=2.0.0=h5eee18b_0
  - libnvfatbin=12.4.99=0
  - libnvfatbin-dev=12.4.99=0
  - libnvjitlink=12.4.99=0
  - libnvjitlink-dev=12.4.99=0
  - libnvjpeg=12.3.1.89=0
  - libnvjpeg-dev=12.3.1.89=0
  - libnvjpeg-static=12.3.1.89=0
  - libsanitizer=14.3.0=hd08acf3_7
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-devel_linux-64=14.3.0=h85bb3a7_107
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - nsight-compute=2024.1.0.13=0
  - openssl=3.6.0=h26f9b46_0
  - pip=25.3=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.19=h6fa692b_0
  - readline=8.3=hc2a1206_0
  - sqlite=3.51.0=h2a70700_0
  - sysroot_linux-64=2.34=h087de78_2
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - addict==2.4.0
      - aliyun-python-sdk-core==2.16.0
      - aliyun-python-sdk-kms==2.16.5
      - cachetools==6.2.2
      - certifi==2025.11.12
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.3.1
      - colorama==0.4.6
      - contourpy==1.3.2
      - crcmod==1.7
      - cryptography==46.0.3
      - cycler==0.12.1
      - descartes==1.1.0
      - filelock==3.19.1
      - fire==0.7.1
      - fonttools==4.60.1
      - fsspec==2025.9.0
      - idna==3.11
      - jinja2==3.1.6
      - jmespath==0.10.0
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - markdown==3.10
      - markdown-it-py==4.0.0
      - markupsafe==2.1.5
      - matplotlib==3.10.7
      - mdurl==0.1.2
      - mmcv==2.1.0
      - mmengine==0.10.7
      - model-index==0.1.11
      - mpmath==1.3.0
      - networkx==3.3
      - ninja==1.13.0
      - numpy==1.26.4
      - nuscenes-devkit==1.2.0
      - nvidia-cublas-cu12==12.4.2.65
      - nvidia-cuda-cupti-cu12==12.4.99
      - nvidia-cuda-nvrtc-cu12==12.4.99
      - nvidia-cuda-runtime-cu12==12.4.99
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.0.44
      - nvidia-curand-cu12==10.3.5.119
      - nvidia-cusolver-cu12==11.6.0.99
      - nvidia-cusparse-cu12==12.3.0.142
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.4.99
      - nvidia-nvtx-cu12==12.4.99
      - opencv-python==4.10.0.84
      - opencv-python-headless==4.11.0.86
      - opendatalab==0.0.10
      - openmim==0.3.9
      - openxlab==0.1.3
      - ordered-set==4.1.0
      - oss2==2.17.0
      - packaging==24.2
      - pandas==2.2.3
      - parameterized==0.9.0
      - pillow==11.3.0
      - platformdirs==4.5.0
      - psutil==7.1.3
      - pycocotools==2.0.10
      - pycparser==2.23
      - pycryptodome==3.23.0
      - pygments==2.19.2
      - pyparsing==3.2.5
      - pyquaternion==0.9.9
      - python-dateutil==2.9.0.post0
      - pytz==2023.4
      - pyyaml==6.0.3
      - requests==2.28.2
      - rich==13.4.2
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - setuptools==60.2.0
      - shapely==2.0.7
      - six==1.17.0
      - sympy==1.14.0
      - tabulate==0.9.0
      - termcolor==3.2.0
      - threadpoolctl==3.6.0
      - tomli==2.3.0
      - torch==2.1.2+cu121
      - torchvision==0.16.2+cu121
      - tqdm==4.65.2
      - triton==2.1.0
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - urllib3==1.26.20
      - yapf==0.43.0
prefix: /home/cernanskyr/.conda/envs/xmem_
